import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ao1k9k5jk.accounts.ondemand.com/oauth2/authorize?client_id=2fad98f3-610b-4304-bf84-83187c448577&response_type=code&redirect_uri=https%3A%2F%2Fmedifarma-portal-qa-63shgxes.authentication.us10.hana.ondemand.com%2Flogin%2Fcallback%2Fsap.custom&state=bfcjWzYV39&code_challenge=0qneEqnuTtrqUiVY7PqLZJsPyBeSxiJxFVgZII_zEuE&code_challenge_method=S256&scope=email+openid+profile&nonce=19gRDAyZ0Tu3');
  await page.getByRole('textbox', { name: 'Correo electrónico o nombre' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico o nombre' }).fill('pierre.galvez@seidor.com');
  await page.getByText('Correo electrónico o nombre de usuario Contraseña').click();
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Pavilion2371126.@');
  await page.getByRole('main').click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('link', { name: 'Registro de Manufactura' }).click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('textbox', { name: 'Lote' }).click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('textbox', { name: 'Lote' }).fill('2040196');
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('textbox', { name: 'Lote' }).press('Enter');
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('textbox', { name: 'Lote' }).press('Enter');
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('textbox', { name: 'Lote' }).press('Enter');
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('textbox', { name: 'Lote' }).press('Enter');
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('gridcell', { name: '1020' }).click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('gridcell', { name: 'Navegación' }).click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByLabel('Opciones de selección').click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByText('1', { exact: true }).click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('button', { name: 'Confirmar' }).click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().locator('[id="__box7-__table5-0"]').click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByRole('row', { name: 'EVITAR EL INGRESO AL AREA DE' }).getByLabel('Opciones').click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByText('Historial por paso').click();
  await page.locator('iframe[title="Aplicación"]').contentFrame().getByLabel('Historial por paso - EVITAR').getByRole('button', { name: 'Cerrar' }).click();
  await page.getByRole('button', { name: 'Logotipo de SAP' }).click();
  await page.getByRole('button', { name: 'Perfil de Pierre Galvez' }).click();
  await page.getByText('Salir').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.goto('https://medifarma-portal-qa-63shgxes.cpp.cfapps.us10.hana.ondemand.com/logoff.html?siteAlias=portalqas&sap-language=es-ES');
});